server:
  port: 9004
spring:
  application:
    name: tensquare-article # 指定服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.128:3306/tensquare_article?CharacterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 192.168.25.128
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 192.168.25.128
eureka:
  client:
    service-url:
      defaultZone: http://192.168.25.128:6868/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
