server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.13.38.37:3306/tensquare_friend?CharacterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 106.13.38.37
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 106.13.38.37
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://106.13.38.37:6868/eureka/
  instance:
    prefer-ip-address: true
