server:
  port: 9002
spring:
  application:
    name: tensquare-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.13.38.37:3306/tensquare_recruit?CharacterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 106.13.38.37
eureka:
  client:
    service-url:
      defaultZone: http://106.13.38.37:6868/eureka/
  instance:
    prefer-ip-address: true
