server:
  port: 9007
spring:
  application:
    name: tensquare-search
  data:
    elasticsearch:
      cluster-nodes: 192.168.25.128:9300
  rabbitmq:
    host: 192.168.25.128
eureka:
  client:
    service-url:
      defaultZone: http://192.168.25.128:6868/eureka/
  instance:
    prefer-ip-address: true
