server:
  port: 9007
spring:
  application:
    name: tensquare-search
  data:
    elasticsearch:
      cluster-nodes: 106.13.38.37:9300
  rabbitmq:
    host: 106.13.38.37
eureka:
  client:
    service-url:
      defaultZone: http://106.13.38.37:6868/eureka/
  instance:
    prefer-ip-address: true
