server:
  port: 9009
spring:
  application:
    name: tensquare_sms
  rabbitmq:
    host: 192.168.25.128
aliyun:
  sms:
    accessKeyId: 
    accessKeySecret: 
    template_code: SMS_183267908
    sign_name: 追影子的人
