server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.25.128
      database: spitdb
  redis:
    host: 192.168.25.128
  rabbitmq:
    host: 192.168.25.128
eureka:
  client:
    service-url:
      defaultZone: http://192.168.25.128:6868/eureka/
  instance:
    prefer-ip-address: true
