server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 106.13.38.37
      database: spitdb
  redis:
    host: 106.13.38.37
  rabbitmq:
    host: 106.13.38.37
eureka:
  client:
    service-url:
      defaultZone: http://106.13.38.37:6868/eureka/
  instance:
    prefer-ip-address: true
